print("what is your fathers name")
fathers_name=input("kalanguka")
print("how old is your father")
fathers_age=input(50)
print("what is your mothers name")
mothers_name=input("jane")
print("how old is your mother")
mothers_age=input(40)
print("the sum of father and mothers age")
print("the difference of fathers and mothers age")
sum=raw_input("fathers age + mothers age")
difference=input("fathers age-mothers age")

